"""Sprite frame registry for the Varedura Roomba mascot.

Each state maps to a list of PNG image paths (generated by generate_sprites.py).
The renderer loads these via rich-pixels at display time.
"""

from __future__ import annotations

from pathlib import Path

IMAGES_DIR = Path(__file__).parent / "images"

# ─── State enum ──────────────────────────────────────────────────────


class STATES:
    """Mascot animation states."""

    IDLE = "idle"
    WORKING = "working"
    SUCCESS = "success"
    ERROR = "error"
    WAVE = "wave"
    SCANNING = "scanning"


# ─── Frame registry (image paths per state) ─────────────────────────

def _paths(state: str) -> list[Path]:
    """Return sorted list of sprite PNGs for a given state."""
    return sorted(IMAGES_DIR.glob(f"{state}_*.png"))


FRAMES: dict[str, list[Path]] = {
    STATES.IDLE: _paths("idle"),
    STATES.WORKING: _paths("working"),
    STATES.SUCCESS: _paths("success"),
    STATES.ERROR: _paths("error"),
    STATES.WAVE: _paths("wave"),
    STATES.SCANNING: _paths("scanning"),
}

# Sprite display size (columns x rows in terminal)
SPRITE_SIZE = (48, 48)
